version: '3'
services:
  app:
    build: .
    container_name: papersync
    volumes:
      - papersync_data:/app/repo
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    user: root
    command: sh -c "chmod +x /app/docker-startup.sh && /app/docker-startup.sh"

volumes:
  papersync_data: